version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0

parameters:
  role-name:
    type: string
    default: "arn:aws:iam::992382483259:role/fieldeng_circleci_labs_oidc_oauth_role" 
  aws-default-region:
    type: string
    default: "us-east-1"

commands:
  aws-auth-setup:
    steps:
      - aws-cli/setup:
          region: << pipeline.parameters.aws-default-region >>
          role_arn: << pipeline.parameters.role-name >>
          role_session_name: "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}"

jobs:
  packer-build:
    docker:
      - image: public.ecr.aws/hashicorp/packer:1.12
    resource_class: small
    steps:
      - checkout
      - aws-auth-setup
      - run: 
          name: Initialize Packer
          command: packer init .
      - run: 
          name: Build Packer Image
          command: packer build ubuntu-docker.pkr.hcl

workflows:
  packer:
    jobs:
      - packer-build
